apiVersion: v1
kind: Service
metadata:
  name: ybhack-service
  namespace: tools
  labels:
    app: ybhack
spec:
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: ybhack
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ybhack-deploy
  namespace: tools
spec:
  selector:
    matchLabels:
      app: ybhack
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ybhack
    spec:
      containers:
      - name: ybhack
        image: sybex/ybhack-frontend:0.${DRONE_BUILD_NUMBER}
        imagePullPolicy: Always
        env:
        - name: ELASTIC_USER
          valueFrom:
            secretKeyRef:
              name: ybhack-secret
              key: user
        - name: ELASTIC_PASS
          valueFrom:
            secretKeyRef:
              name: ybhack-secret
              key: pass
        resources:
          limits:
            cpu: 1000m
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 10Mi
        ports:
        - containerPort: 5000
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /healthz
            port: 5000
          initialDelaySeconds: 2
          timeoutSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5000
          initialDelaySeconds: 5
          timeoutSeconds: 10
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ybhack-ingress
  namespace: tools
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - ybfame.dreng.ch
    secretName: tls-ybhack-ingress
  rules:
  - host: ybfame.dreng.ch
    http:
      paths:
      - path: /
        backend:
          serviceName: ybhack-service
          servicePort: 5000
