kind: pipeline
name: ybhack-fame-calc

steps:
- name: build
  image: plugins/docker
  settings:
    repo: sybex/ybhack-frontend
    cache_from: sybex/ybhack-frontend
    tags:
      - latest
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    dockerfile: frontend/Dockerfile

- name: deploy
  image: sybex/drone-kubectl
  settings:
    kubernetes_server:
      from_secret: kubernetes_server_url
    kubernetes_token:
      from_secret: kubernetes_server_token
  commands:
    - kubectl apply -f frontend/deployment.yaml
