kind: pipeline
name: frontend

steps:
- name: build
  image: plugins/docker
  settings:
    repo: sybex/ybhack-frontend
    cache_from: sybex/ybhack-frontend
    tags:
      - latest
      - 0.${DRONE_BUILD_NUMBER}-beta
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    dockerfile: frontend/Dockerfile

- name: deploy
  image: sybex/drone-kubectl
  settings:
    kubernetes_server:
      from_secret: kubernetes_server_url
    kubernetes_token:
      from_secret: kubernetes_server_token
  commands:
    - kubectl apply -f frontend/deployment.yaml
---
kind: pipeline
name: crawler

steps:
- name: build
  image: plugins/docker
  settings:
    repo: sybex/ybhack-crawler
    cache_from: sybex/ybhack-crawler
    tags:
      - latest
      - 0.${DRONE_BUILD_NUMBER}-beta
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    dockerfile: crawler/Dockerfile

- name: deploy
  image: sybex/drone-kubectl
  settings:
    kubernetes_server:
      from_secret: kubernetes_server_url
    kubernetes_token:
      from_secret: kubernetes_server_token
  commands:
    - kubectl apply -f crawler/deployment.yaml
---
kind: pipeline
name: scraper

steps:
- name: compile
  image: adoptopenjdk/maven-openjdk11
  commands:
    - cd insta-scrape
    - mvn package

- name: build
  image: plugins/docker
  settings:
    repo: sybex/ybhack-scraper
    cache_from: sybex/ybhack-scraper
    tags:
      - latest
      - 0.${DRONE_BUILD_NUMBER}-beta
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    dockerfile: insta-scrape/Dockerfile

- name: deploy
  image: sybex/drone-kubectl
  settings:
    kubernetes_server:
      from_secret: kubernetes_server_url
    kubernetes_token:
      from_secret: kubernetes_server_token
  commands:
    - kubectl apply -f insta-scrape/cronjob.yaml
