apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: scraper
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ybhack
            image: sybex/ybhack-scraper:0.${DRONE_BUILD_NUMBER}-beta
          restartPolicy: Never
